/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import com.sun.org.apache.xalan.internal.xsltc.compiler.util.StringStack;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import newpackage.hepbo.DataVali;
import newpackage.hepbo.MessageDialong;
import newpackage.nguoidung.BangDiem;
import newpackage.nguoidung.SinhVien;
import newpackage.nguoidung.dao.BangDiemDao;
import newpackage.nguoidung.dao.SinhVienDao;

/**
 *
 * @author ACER
 */
public class Bangdiem extends javax.swing.JPanel {

    private mainfrom parenForm;
    private DefaultTableModel tableModel;

    /**
     * Creates new form Bangdiem
     */
    public Bangdiem() {
        initComponents();
        initTable();
        loadBangDiem();
    }
    private void loadBangDiem(){
        try {
            BangDiemDao dao = new BangDiemDao();
            List<BangDiem> list = dao.findTop(3);
            tableModel.setRowCount(0);
            for (BangDiem x : list) {
               tableModel.addRow(new Object[]{
                   x.getMaSinhVien(),x.getTiengAnh(),x.getTinHoc(),x.getGDTC(),
                   (x.getTiengAnh()+x.getTinHoc()+x.getGDTC())/3
               });
            }
            tableModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialong.showErrorDialog(parenForm, e.getMessage(), "Lỗi");
        }
    }
    
    private void initTable(){
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{
        "Mã Sinh Viên","Tiếng Anh","Tin Học","GDTC","Điểm TB"
        });
        
        tblGpa.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMasinhvien = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtTienganh = new javax.swing.JTextField();
        txtTinhọc = new javax.swing.JTextField();
        txtGDTC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblGpa = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnNhapmoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGpa = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setText("QUẢN LÝ ĐIỂM");

        jLabel2.setText("Mã sinh viên");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly_app/icon/Camera.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel3.setText("Mã sinh viên");

        jLabel4.setText("Họ tên");

        jLabel5.setText("Tiếng anh");

        jLabel6.setText("Tin học");

        jLabel7.setText("GDTC");

        txtMasinhvien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMasinhvienFocusLost(evt);
            }
        });

        txtTienganh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTienganhFocusLost(evt);
            }
        });

        txtTinhọc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblGpaFocusLost(evt);
            }
        });

        txtGDTC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblGpaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(txtTienganh, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMasinhvien))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46)
                        .addComponent(txtHoten))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTinhọc)
                            .addComponent(txtGDTC))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTienganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTinhọc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jLabel8.setText("Điểm TB");

        lblGpa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGpa.setText("9.5");
        lblGpa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblGpaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblGpa)
                        .addGap(8, 8, 8)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(lblGpa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNhapmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly_app/icon/Funny.png"))); // NOI18N
        btnNhapmoi.setText("Nhập mới");
        btnNhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapmoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly_app/icon/Accept.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly_app/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly_app/icon/Edit.png"))); // NOI18N
        btnCapnhat.setText("Cập nhật ");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        tblGpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGpaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGpa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnNhapmoi)
                                .addGap(18, 18, 18)
                                .addComponent(btnLuu)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapnhat))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapnhat, btnLuu, btnNhapmoi, btnXoa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapmoi)
                    .addComponent(btnLuu)
                    .addComponent(btnXoa)
                    .addComponent(btnCapnhat))
                .addGap(16, 16, 16)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapmoiActionPerformed
        txtTienganh.setText("");
        txtTinhọc.setText("");
        txtHoten.setText("");
        txtMasinhvien.setText("");
        txtGDTC.setText("");
    }//GEN-LAST:event_btnNhapmoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        StringBuilder sb = new StringBuilder();
        DataVali.validateEmpty(txtMasinhvien, sb, "Chưa nhập mã Sv");
        DataVali.validateEmpty(txtTienganh, sb, "Chưa nhập Tiếng anh");
        DataVali.validateEmpty(txtTinhọc, sb, "Chưa nhập Tin Học");
        DataVali.validateEmpty(txtGDTC, sb, "Chưa nhập mã GDTC");
        if (sb.length() > 0) {
            MessageDialong.showErrorDialog(parenForm, sb.toString(), "lỗi");
            return;
        }
        try {
            BangDiem bd = new BangDiem();
            bd.setMaSinhVien(txtMasinhvien.getText());
            bd.setTiengAnh(Float.parseFloat(txtTienganh.getText()));
            bd.setTinHoc(Float.parseFloat(txtTinhọc.getText()));
            bd.setGDTC(Float.parseFloat(txtGDTC.getText()));

            BangDiemDao dao = new BangDiemDao();
            if (dao.findByMaSinhVien(txtMasinhvien.getText()) != null) {
                if (MessageDialong.showConfirmDialog(parenForm, "bạn có muốn cập nhật điểm không", "hỏi")==JOptionPane.NO_OPTION) {
                    return;
                }
                if (dao.insert(bd)) {
                    MessageDialong.showMessageDialog(parenForm, "Bảng điểm đã dc cập nhật", "Thông Báo ");
                } else {
                    MessageDialong.showMessageDialog(parenForm, "Bảng điểm không dc cập nhật", "Thông Báo ");
                }
            } else
            { 
                if (dao.insert(bd)) {
                MessageDialong.showMessageDialog(parenForm, "Bảng điểm đã dc lưu", "Thông Báo ");
            } else {
                MessageDialong.showMessageDialog(parenForm, "Bảng điểm không dc lưu", "Thông Báo ");
            }}
loadBangDiem();
initTable();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialong.showErrorDialog(parenForm, e.getMessage(), "Lỗi");
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    private void txtMasinhvienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMasinhvienFocusLost
        try {
            SinhVienDao dao = new SinhVienDao();
            SinhVien sv =  dao.findByid(txtMasinhvien.getText());
            if (sv != null) {
                txtHoten.setText(sv.getHoTen());
            }
        } catch (Exception e) {
             e.printStackTrace();
            MessageDialong.showErrorDialog(parenForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_txtMasinhvienFocusLost

    private void txtTienganhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTienganhFocusLost
       if(txtTienganh.getText().equals("") ||
               txtTinhọc.getText().equals("") ||
               txtGDTC.getText().equals("")){
           return;
       }
        
        float ta = Float.parseFloat(txtTienganh.getText());
        float tin = Float.parseFloat(txtTinhọc.getText());
        float pt = Float.parseFloat(txtGDTC.getText());
        float avg = (ta + tin + pt)/3; 
        
        String st = String.format("%.2f", avg);
        lblGpa.setText(st);
    }//GEN-LAST:event_txtTienganhFocusLost

    private void lblGpaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblGpaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGpaFocusLost

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            BangDiemDao dao = new BangDiemDao();
            BangDiem bd = dao.findByMaSinhVien(txtTimkiem.getText());
            
            if (bd != null) {
                txtMasinhvien.setText(bd.getMaSinhVien());
                txtTienganh.setText(String.format("%.2f", bd.getTiengAnh()));
                txtTinhọc.setText(String.format("%.2f", bd.getTinHoc()));
                txtGDTC.setText(String.format("%.2f", bd.getGDTC()));
                
                txtMasinhvienFocusLost(null);
                txtTienganhFocusLost(null);
            
            }else{
                MessageDialong.showMessageDialog(parenForm, "Khong timf thấy SV", "thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialong.showErrorDialog(parenForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        btnLuuActionPerformed(evt);
        loadBangDiem();
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            if (txtMasinhvien.getText().equals("")) {
                MessageDialong.showMessageDialog(parenForm, "mã sinh viên chưa nhập ","lỗi" );
                return;
            }
            BangDiemDao dao = new BangDiemDao();
            BangDiem bd = dao.findByMaSinhVien(txtMasinhvien.getText());
            if (bd == null) {
                MessageDialong.showMessageDialog(parenForm, "mã sv ko tồn tại", "lỗi");
                
            }if (MessageDialong.showConfirmDialog(parenForm, "Bạn Muốn xóa điểm à", "Thông báo")== JOptionPane.NO_OPTION) {
                return;
            }
            
            if (dao.deleteByMaSinhVien(txtMasinhvien.getText())) {
                 MessageDialong.showMessageDialog(parenForm, "Điểm đã dc xóa", "Thông báo");
            }else{
               MessageDialong.showMessageDialog(parenForm, "Điểm Khồng dc xóa", "Thông báo"); 
            }
            loadBangDiem();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialong.showErrorDialog(parenForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblGpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGpaMouseClicked
            try {
            int row = tblGpa.getSelectedRow();
            
            if (row >= 0) {
                String id = (String) tblGpa.getValueAt(row, 0);
                BangDiemDao dao = new BangDiemDao();
                BangDiem sv = dao.findByMaSinhVien(id);
                if (sv != null) {
                    txtMasinhvien.setText(sv.getMaSinhVien());
                    txtTienganh.setText(String.format("%.2f", sv.getTiengAnh()));
                    txtTinhọc.setText(String.format("%.2f", sv.getTinHoc()));
                    txtGDTC.setText(String.format("%.2f", sv.getGDTC()));
                    
                }
            }
            
        } catch (Exception e) {
              e.printStackTrace();
            MessageDialong.showErrorDialog(parenForm
                    ,e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblGpaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhapmoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JTable tblGpa;
    private javax.swing.JTextField txtGDTC;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMasinhvien;
    private javax.swing.JTextField txtTienganh;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtTinhọc;
    // End of variables declaration//GEN-END:variables
}
